"""phase 12 security lockout and performance indexes

Revision ID: d399b0d8e66d
Revises: edce7f7976f2
Create Date: 2026-09-27 08:30:47.433678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd399b0d8e66d'
down_revision: Union[str, None] = 'edce7f7976f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_model_record', 'audit_logs', ['model_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_register_id'), 'cash_sessions', ['register_id'], unique=False)
    op.create_index(op.f('ix_deliveries_route_id'), 'deliveries', ['route_id'], unique=False)
    op.create_index(op.f('ix_delivery_lines_delivery_id'), 'delivery_lines', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_routes_driver_id'), 'delivery_routes', ['driver_id'], unique=False)
    op.create_index(op.f('ix_fuel_logs_vehicle_id'), 'fuel_logs', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_order_id'), 'purchase_order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_sale_order_lines_order_id'), 'sale_order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_sale_orders_sales_rep_id'), 'sale_orders', ['sales_rep_id'], unique=False)
    op.create_index(op.f('ix_stock_inventory_lines_inventory_id'), 'stock_inventory_lines', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_stock_moves_dest_warehouse_id'), 'stock_moves', ['dest_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_moves_product_id'), 'stock_moves', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_moves_source_warehouse_id'), 'stock_moves', ['source_warehouse_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoice_lines_invoice_id'), 'supplier_invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_purchase_order_id'), 'supplier_invoices', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_supplier_id'), 'supplier_invoices', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_invoice_id'), 'supplier_payments', ['invoice_id'], unique=False)
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenances_vehicle_id'), 'vehicle_maintenances', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_maintenances_vehicle_id'), table_name='vehicle_maintenances')
    op.drop_index(op.f('ix_vehicle_documents_vehicle_id'), table_name='vehicle_documents')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_supplier_payments_invoice_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_invoices_supplier_id'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_purchase_order_id'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoice_lines_invoice_id'), table_name='supplier_invoice_lines')
    op.drop_index(op.f('ix_stock_moves_source_warehouse_id'), table_name='stock_moves')
    op.drop_index(op.f('ix_stock_moves_product_id'), table_name='stock_moves')
    op.drop_index(op.f('ix_stock_moves_dest_warehouse_id'), table_name='stock_moves')
    op.drop_index(op.f('ix_stock_inventory_lines_inventory_id'), table_name='stock_inventory_lines')
    op.drop_index(op.f('ix_sale_orders_sales_rep_id'), table_name='sale_orders')
    op.drop_index(op.f('ix_sale_order_lines_order_id'), table_name='sale_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_fuel_logs_vehicle_id'), table_name='fuel_logs')
    op.drop_index(op.f('ix_delivery_routes_driver_id'), table_name='delivery_routes')
    op.drop_index(op.f('ix_delivery_lines_delivery_id'), table_name='delivery_lines')
    op.drop_index(op.f('ix_deliveries_route_id'), table_name='deliveries')
    op.drop_index(op.f('ix_cash_sessions_register_id'), table_name='cash_sessions')
    op.drop_index('ix_audit_logs_model_record', table_name='audit_logs')
    # ### end Alembic commands ###
